site_name: CMMC
edit_uri: https://github.com/Wang-Bioinformatics-Lab/CMMC_Website/edit/master/docs/
repo_name: CMMC_Website
repo_url: https://github.com/Wang-Bioinformatics-Lab/CMMC_Website

nav:
    - Home Page: index.md
    - Documentation:
        - Getting a USI: get_USI.md
        - CMMC Deposition Workflow: deposition_documentation.md
        - Network Enrichment analysis: network_enrichment.md
    - CMMC Workshops/Training: workshops.md
    - Contact and Office Hours: contact.md
    
theme:
    name: material
    palette:
        primary: '#003DA5'
        accent: '#FFB81C'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/Wang-Bioinformatics-Lab/CMMC_Website'

plugins:
    - search
    - git-revision-date-localized:
        type: datetime

markdown_extensions:
    - toc:
        permalink: true
    - admonition

extra:
  analytics:
    provider: google
    property: XXX
